### ISSUE TITLE
[Bug] Render Issues, Resource Packs

### ISSUE THREAD

**Issue by aschmois** [Ordinastie/MalisisDoors#28]
When I load a texture pack higher than the normal 16x this happens:

![](http://i.imgur.com/vEwyMaC.png)
![](http://i.imgur.com/NE8ZtgO.png)

The textures just disappear! It happens only for rusty ladder and rusty hatch.

This is how it should look like (sometimes it works, don't ask me why)

![](http://i.imgur.com/ACNUWYh.png)
![](http://i.imgur.com/PUfYEvW.png)
![](http://i.imgur.com/8HvPUd6.png)

**Comment by Ordinastie** [comment]
That's an issue that was resolved long time ago. Please download latest version.

**Comment by aschmois** [comment]
I did download the newest version, same problem applies.

**Comment by xBPMx** [comment]
iv the same problem as aschmois 
but texture pack makes no difference "for me"
the hatch and ladder have the same render bug all the time

take out OptiFine_1.7.10_HD_U_B5
and the render is fine,....

added 
OptiFine_1.7.10_HD_B6 and that works to, but with an fps drop

updated to OptiFine_1.7.10_HD_U_B6 and the same render bug is back :(


1.7.10-Forge10.13.2.1291
malisiscore-1.7.10-0.11.4
malisisdoors-1.7.10-1.7.1
